
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dowapi_development
  username: tomgdow
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: dowapi_test
  username: tomgdow
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
  port: 5432
#
production:
  <<: *default
  database: dowapi_production
  username: tomgdow
  password: <%= ENV['POSTGRES_PASSWORD'] %>
